# GitHub reusable workflow for CI/CD of Go applications

name: CI/CD Go

# this is a reusable workflow
on:
  workflow_call:
    inputs:
      go-version:
        type: string
        required: false
        description: Go version to use
        default: 1.21.6
      golangci-lint-version:
        type: string
        required: false
        description: golangci-lint version to use
        default: 1.56.2
      golangci-lint-timeout:
        type: string
        required: false
        description: golangci-lint timeout
        default: 5m
      make-target-check:
        type: string
        required: false
        description: Make target to run for checking
        default: check

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: false
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v${{ inputs.golangci-lint-version }}
          args: |
            --timeout=${{ inputs.golangci-lint-timeout }}
      - name: Check
        run: make ${{ inputs.make-target-check }}
